backend:
  name: git-gateway
  branch: master
media_folder: static/images
public_folder: /images
collections:
  - name: config
    label: Config
    files:
      - name: config
        label: Config
        file: site-metadata.json
        fields:
          - widget: string
            name: title
            label: Title
            required: true
            hint: Site title
          - widget: object
            name: menu
            label: Menu Configuration
            required: false
            fields:
              - widget: list
                name: actions
                label: Menu Action Buttons
                required: false
                hint: The action buttons displayed at the bottom of the menu
                fields:
                  - widget: string
                    name: label
                    label: Button Label
                    required: true
                    hint: The text displayed inside the button
                  - widget: string
                    name: url
                    label: Button URL
                    required: false
                  - widget: boolean
                    name: is_scrolly
                    label: Is Scrolly
                    required: false
                    default: false
                    hint: >-
                      Gives the button a scroll animation (if the button URL is
                      a section ID)
                  - widget: boolean
                    name: is_primary
                    label: Is Primary
                    required: false
                    default: false
                    hint: Gives the button a primary color scheme
          - widget: object
            name: social
            label: Footer Social Section Configuration
            required: false
            fields:
              - widget: boolean
                name: enabled
                label: Enabled
                required: false
                default: false
                hint: Displays the social section in the page footer
              - widget: string
                name: title
                label: Section Title
                required: false
                hint: The bold text displayed at the top of the section
              - widget: markdown
                name: social_content
                label: Section Text
                required: false
                hint: The text displayed below the section title
              - widget: list
                name: social_links
                label: Social Media
                required: false
                hint: >-
                  A list of social media icons displayed along the bottom of the
                  section
                fields:
                  - widget: string
                    name: title
                    label: Icon Title
                    required: true
                  - widget: string
                    name: icon
                    label: Icon
                    required: true
                    hint: Font Awesome icon
                  - widget: string
                    name: link_url
                    label: URL
                    required: false
          - widget: object
            name: footer
            label: Footer Configuration
            required: false
            fields:
              - widget: boolean
                name: enable_contact_section
                label: Enable Contact Section
                required: false
                default: false
                hint: Displays the contact section in the page footer
              - widget: string
                name: line_phrase
                label: Copyright Phrase
                required: false
                hint: The text displayed beside the page copyright
  - name: home
    label: Home
    files:
      - name: home
        label: Home
        file: src/pages/index.md
        fields:
          - widget: string
            name: title
            label: Page Title
            required: true
          - widget: list
            name: sections
            label: Sections
            required: false
            hint: Home Sections
            types:
              - name: intro
                widget: object
                label: Intro Section
                fields:
                  - widget: markdown
                    name: content
                    label: Section Content
                    required: false
                    hint: The text displayed as section content
                  - widget: list
                    name: actions
                    label: Section Action Buttons
                    required: false
                    fields:
                      - widget: string
                        name: label
                        label: Button Label
                        required: true
                        hint: The text displayed inside the button
                      - widget: string
                        name: url
                        label: Button URL
                        required: false
                      - widget: boolean
                        name: is_scrolly
                        label: Is Scrolly
                        required: false
                        default: false
                        hint: >-
                          Gives the button a scroll animation (if the button URL
                          is a section ID)
                      - widget: boolean
                        name: is_primary
                        label: Is Primary
                        required: false
                        default: false
                        hint: Gives the button a primary color scheme
                  - widget: string
                    name: title
                    label: Section Title
                    required: true
                    default: Reflex
                    hint: The bold text displayed at the top of the section
                  - widget: image
                    name: img_path
                    label: Image
                    required: false
                    hint: The image displayed on the left side of the section
                  - widget: hidden
                    name: component
                    label: Section Component
                    required: true
                    default: Intro
              - name: features
                widget: object
                label: Features Section
                fields:
                  - widget: markdown
                    name: content
                    label: Section Content
                    required: false
                    hint: The text displayed as section content
                  - widget: list
                    name: actions
                    label: Section Action Buttons
                    required: false
                    fields:
                      - widget: string
                        name: label
                        label: Button Label
                        required: true
                        hint: The text displayed inside the button
                      - widget: string
                        name: url
                        label: Button URL
                        required: false
                      - widget: boolean
                        name: is_scrolly
                        label: Is Scrolly
                        required: false
                        default: false
                        hint: >-
                          Gives the button a scroll animation (if the button URL
                          is a section ID)
                      - widget: boolean
                        name: is_primary
                        label: Is Primary
                        required: false
                        default: false
                        hint: Gives the button a primary color scheme
                  - widget: string
                    name: title
                    label: Section Title
                    required: true
                    default: Ipsum malesuada
                    hint: The bold text displayed at the top of the section
                  - widget: markdown
                    name: subtitle
                    label: Section Subtitle
                    required: false
                    hint: The text displayed below the section title
                  - widget: list
                    name: symbol_display
                    label: Icon Circles
                    required: false
                    hint: The icons displayed below the section subtitle
                    fields:
                      - widget: string
                        name: title
                        label: Icon Title
                        required: true
                      - widget: string
                        name: icon
                        label: Icon
                        required: true
                        hint: Font Awesome icon
                  - widget: hidden
                    name: component
                    label: Section Component
                    required: true
                    default: Features
              - name: spotlight
                widget: object
                label: Spotlight Section
                fields:
                  - widget: markdown
                    name: content
                    label: Section Content
                    required: false
                    hint: The text displayed as section content
                  - widget: list
                    name: actions
                    label: Section Action Buttons
                    required: false
                    fields:
                      - widget: string
                        name: label
                        label: Button Label
                        required: true
                        hint: The text displayed inside the button
                      - widget: string
                        name: url
                        label: Button URL
                        required: false
                      - widget: boolean
                        name: is_scrolly
                        label: Is Scrolly
                        required: false
                        default: false
                        hint: >-
                          Gives the button a scroll animation (if the button URL
                          is a section ID)
                      - widget: boolean
                        name: is_primary
                        label: Is Primary
                        required: false
                        default: false
                        hint: Gives the button a primary color scheme
                  - widget: string
                    name: title
                    label: Section Title
                    required: true
                    default: Duis torquent
                    hint: The bold text displayed at the top of the section
                  - widget: markdown
                    name: subtitle
                    label: Section Subtitle
                    required: false
                    hint: The text displayed below the section title
                  - widget: hidden
                    name: component
                    label: Section Component
                    required: true
                    default: Spotlight
              - name: mission
                widget: object
                label: Mission Section
                fields:
                  - widget: markdown
                    name: content
                    label: Section Content
                    required: false
                    hint: The text displayed as section content
                  - widget: list
                    name: actions
                    label: Section Action Buttons
                    required: false
                    fields:
                      - widget: string
                        name: label
                        label: Button Label
                        required: true
                        hint: The text displayed inside the button
                      - widget: string
                        name: url
                        label: Button URL
                        required: false
                      - widget: boolean
                        name: is_scrolly
                        label: Is Scrolly
                        required: false
                        default: false
                        hint: >-
                          Gives the button a scroll animation (if the button URL
                          is a section ID)
                      - widget: boolean
                        name: is_primary
                        label: Is Primary
                        required: false
                        default: false
                        hint: Gives the button a primary color scheme
                  - widget: string
                    name: title
                    label: Section Title
                    required: true
                    default: Amet ullamcorper
                    hint: The bold text displayed at the top of the section
                  - widget: hidden
                    name: component
                    label: Section Component
                    required: true
                    default: Mission
          - widget: hidden
            name: template
            label: Template
            required: true
            default: home
          - widget: object
            name: menus
            label: Home Menus
            required: false
            hint: Which menus should this page show up in
            fields:
              - widget: object
                name: main
                label: Main menu item
                required: false
                hint: Main menu item for this page
                fields:
                  - widget: string
                    name: title
                    label: Title
                    required: false
                    hint: The title of the menu item
                  - widget: number
                    name: weight
                    label: Weight
                    required: false
                    hint: Position for sorting
                    valueType: int
  - name: page
    label: Pages
    folder: src/pages/
    filter:
      field: template
      value: page
    create: true
    extension: md
    slug: '{{slug}}'
    fields:
      - widget: string
        name: title
        label: Page Title
        required: true
      - widget: markdown
        name: subtitle
        label: Page Subtitle
        required: false
        hint: The text displayed below the page title
      - widget: image
        name: img_path
        label: Content Image
        required: false
        hint: The image displayed in the page content
      - widget: hidden
        name: template
        label: Template
        required: true
        default: page
      - widget: object
        name: menus
        label: Page Menus
        required: false
        hint: Which menus should this page show up in
        fields:
          - widget: object
            name: main
            label: Main menu item
            required: false
            hint: Main menu item for this page
            fields:
              - widget: string
                name: title
                label: Title
                required: false
                hint: The title of the menu item
              - widget: number
                name: weight
                label: Weight
                required: false
                hint: Position for sorting
                valueType: int
      - widget: markdown
        name: body
        label: Content
        required: false
        hint: Page content
  - name: post
    label: Posts
    folder: src/pages/posts
    filter:
      field: template
      value: page
    create: true
    extension: md
    slug: '{{slug}}'
    fields:
      - widget: string
        name: title
        label: Page Title
        required: true
      - widget: markdown
        name: subtitle
        label: Page Subtitle
        required: false
        hint: The text displayed below the page title
      - widget: markdown
        name: excerpt
        label: Post Excerpt
        required: false
        hint: The excerpt displayed in the spotlights section of the home page
      - widget: image
        name: img_path
        label: Content Image
        required: false
        hint: The image displayed in the page content
      - widget: string
        name: post_button_label
        label: Spotlights Button label
        required: false
        hint: The text displayed in the home spotligh button
      - widget: date
        name: date
        label: Post Date
        required: true
      - widget: hidden
        name: template
        label: Template
        required: true
        default: page
      - widget: object
        name: menus
        label: Post Menus
        required: false
        hint: Which menus should this page show up in
        fields:
          - widget: object
            name: main
            label: Main menu item
            required: false
            hint: Main menu item for this page
            fields:
              - widget: string
                name: title
                label: Title
                required: false
                hint: The title of the menu item
              - widget: number
                name: weight
                label: Weight
                required: false
                hint: Position for sorting
                valueType: int
      - widget: markdown
        name: body
        label: Content
        required: false
        hint: Page content
  - name: elements
    label: Elements
    files:
      - name: elements
        label: Elements
        file: src/pages/elements.md
        fields:
          - widget: string
            name: title
            label: Page Title
            required: true
          - widget: hidden
            name: template
            label: Template
            required: true
            default: elements
          - widget: object
            name: menus
            label: Elements Menus
            required: false
            hint: Which menus should this page show up in
            fields:
              - widget: object
                name: main
                label: Main menu item
                required: false
                hint: Main menu item for this page
                fields:
                  - widget: string
                    name: title
                    label: Title
                    required: false
                    hint: The title of the menu item
                  - widget: number
                    name: weight
                    label: Weight
                    required: false
                    hint: Position for sorting
                    valueType: int
